### ISSUE TITLE
Tracking issue for complete rewrite

### ISSUE THREAD

**Issue by flori4nk** [flori4nk/VelocityAutoReconnect#22]
- [ ] Rewrite player management using actual Queue (most likely ArrayDequeue)
- [ ] Reimplement reconnection task accordingly
- [ ] Partial reimplementation of ConnectionListener
- [ ] Partial reimplementation of KickListener
